name: camera_plus
description: "A camera package"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  mockito: ^5.4.6
  dev: ^1.0.0
  build_runner: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
